ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\ak\Desktop\Note files\postman run collection.txt")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlClick("Open","","Button1")